name: Build Area Calculator

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          architecture: "x64"
          
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build Executable
        run: uvx nuitka --standalone --onefile --follow-imports --output-dir="./output/" Area_Calculator.py

      - name: Copy README
        run: cp README.md ./output/README.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Area_Calculator
          path: ./output/
          
